<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>Library</OutputType>
        <TargetFramework>net462</TargetFramework>
        <RootNamespace>QuickLook.Plugin.ThreeDMaster</RootNamespace>
        <AssemblyName>QuickLook.Plugin.ThreeDMaster</AssemblyName>
        <Platforms>AnyCPU;x64</Platforms>
        <UseWPF>true</UseWPF>
        <UseWindowsForms>true</UseWindowsForms>
        <LangVersion>latest</LangVersion>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
        <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
        <GenerateTargetFrameworkAttribute>false</GenerateTargetFrameworkAttribute>
        <DebugType>full</DebugType>
    </PropertyGroup>

    <PropertyGroup Condition="'$(Configuration)' == 'Debug'">
        <Optimize>false</Optimize>
        <OutputPath>bin\Debug\</OutputPath>
        <DefineConstants>DEBUG;TRACE</DefineConstants>
    </PropertyGroup>

    <PropertyGroup Condition="'$(Configuration)' == 'Release'">
        <Optimize>true</Optimize>
        <OutputPath>bin\Release\</OutputPath>
        <DefineConstants>TRACE</DefineConstants>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="QuickLook.Common" Version="4.5.0" />
    </ItemGroup>

    <ItemGroup>
        <None Include="QuickLook.Plugin.Metadata.config">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
    </ItemGroup>
</Project>
